### ISSUE TITLE
Children services are not displayed in "My services"

### ISSUE THREAD

**Issue by evenit** [ManageIQ/manageiq-ui-service#100]
Description of problem:
I have nested services: a parent service has children services. Only the top level services are visible in "My Services". When connected to the classic UI, the children services are correctly displayed. Nested services is really useful to create a service hierarchy and allow large scale retirement.

Version-Release number of selected component (if applicable): commit #8665aeb5d34a8de08ad17377d9eb188a5ddac5f0

How reproducible: Always

Steps to Reproduce:
Create nested services. A nested service has a parent_service.

Actual results:
In the classic UI, go in "My Services". All services are displayed as a tree.
In the Self Service UI, go in "My Services". Only the highest level service is displayed.

Expected results:
In both UIs, all services are displayed. The tree widget may not fit the layout of SSUI.

**Comment by chriskacerguis** [comment]
@serenamarie125 Can you please have someone take a look?  Let me know who can I can assign this to them

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 can you please take a look at this issue?

/cc @serenamarie125

**Comment by jeff-phillips-18** [comment]
@chriskacerguis @serenamarie125  Looks like the request is to modify the services section to show a tree view or an expanded view for the services. I believe we would want a UX design for this and a Dev story so that it can be properly prioritized.

**Comment by chriskacerguis** [comment]
Sounds reasonable to me

**Comment by chriskacerguis** [comment]
Changing from bug to enhancement.

**Comment by serenamarie125** [comment]
@jeff-phillips-18 It looks like the DB which you gave has a service like this.

Here's what it looks like in the Ops UI:

<img width="1482" alt="screen shot 2016-10-18 at 10 30 58 am" src="https://cloud.githubusercontent.com/assets/12504403/19484766/5223b084-951e-11e6-92b3-4490c065ec1e.png">

<img width="1483" alt="screen shot 2016-10-18 at 10 33 28 am" src="https://cloud.githubusercontent.com/assets/12504403/19484770/5a5071e8-951e-11e6-9d81-4b8eb2171f84.png">

Here's what it currently looks like in the Self Service UI:

<img width="1615" alt="screen shot 2016-10-18 at 10 31 21 am" src="https://cloud.githubusercontent.com/assets/12504403/19484782/60848b80-951e-11e6-9365-9c2fb29ea571.png">

@jntullo Can you check if there is an API which can determine if a provisioned service has a child service?  If so, we may be able to come up with a solution asap Thanks!

**Comment by jntullo** [comment]
@serenamarie125 Yes it is possible to determine if a provisioned service has a child service.

The specs for this are a good place to start for some examples: 
https://github.com/ManageIQ/manageiq/blob/master/spec/requests/api/services_spec.rb#L20

the request will be `/api/services/:id/vms`

**Comment by evenit** [comment]
Well the 'vms' call will get you the virtual machines, not the other kind
of services, like storage, network, generic... If my memory is correct, you
can get children from automation objects with 'children', not sure it
exists in the API.

@serena : how would you see it implemented from a UX point of view ?

Le 18 oct. 2016 5:52 PM, "Jillian Tullo" <notifications@github.com> a
écrit :

**Comment by evenit** [comment]
Why was it closed? I don't see any PR associated.

**Comment by serenamarie125** [comment]
Agreed @evenit this needs to be addressed.

**Comment by jntullo** [comment]
@evenit never noticed your original comment. But you are correct, it acts similarly - passing `attributes=all_service_children` to a service will return you all of the service children associated with a service.

**Comment by evenit** [comment]
@jntullo  Then it should be possible to inspect them. Is there something that shows only the direct children services. This would allow to "dive in" the service progressively, like within a tree.

@serenamarie125 Has someone worked on the UX for this ? I remember we talked about list views and it sounded promising: http://www.patternfly.org/pattern-library/content-views/list-view/#/expanding-rows. That would also be great for virtual machines inside a service.

**Comment by chriskacerguis** [comment]
This was closed, as we moved everything to Pivotal Tracker.

See here: https://github.com/ManageIQ/manageiq-ui-service/issues/344

Your story is located at: https://www.pivotaltracker.com/story/show/134450733
