### ISSUE TITLE
The service ordering flow should be moved to an overlay panel

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1006]
Description of problem:
When ordering a service, or reordering a service (https://github.com/ManageIQ/manageiq-ui-service/pull/920) the ordering flow is embedded in a page.  This flow should be moved to an overlay panel.  This will improve the user experience by not changing context on the user.

UX should produce mockups for this although an initial quick mockup can be shown here: https://docs.google.com/document/d/16A3j1FYwnCIDppLDB3-lB7cfzcDWOfFlCRy5_b47clg/

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

**Comment by chriskacerguis** [comment]
Per the document (so all can comment):

## Scenarios:

1. User views all orders & selects a request to reorder

1. User is brought through the ordering process, using defaults of the initial request, and given the option to override the values

## Select a request to reorder

<img width="632" alt="screen shot 2017-09-26 at 10 04 47 am" src="https://user-images.githubusercontent.com/2414647/30867638-2c619d6a-a2a2-11e7-949a-34a01d793526.png">

## Go through process, using defaults of the initial request
User is brought through the ordering process in a modal, using defaults of the initial request, and given the option to override the values 

Upon clicking on Add to Shopping Cart, the request is added to the Shopping Cart
<img width="643" alt="screen shot 2017-09-26 at 10 03 50 am" src="https://user-images.githubusercontent.com/2414647/30867656-34d95b40-a2a2-11e7-86f4-ee4d499b268a.png">

**Comment by chriskacerguis** [comment]
Just to make sure we are all on the same page (the doc indicates approval) @Loicavenel are you good with this?

**Comment by Loicavenel** [comment]
That will make more sense for me.

**Comment by chriskacerguis** [comment]
@serenamarie125 since you put this in I'm adding the UX approved label

**Comment by serenamarie125** [comment]
@chriskacerguis I'd like to have a real design for this.  I had a "quick" mockup in the initial Duplicate Order, and that wasn't pursued for 4.6.  Let's make sure we have the appropriate design before you scope and implement this.

**Comment by chriskacerguis** [comment]
@serenamarie125 ok.

Closing this, and tracking here: https://bugzilla.redhat.com/show_bug.cgi?id=1507079
