### ISSUE TITLE
Add RBAC visibility to the help menu

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1028]
@chalettu can you please add the RBAC you created here: https://github.com/ManageIQ/manageiq-ui-service/issues/882 for the help menu?  If they have access, please show it, otherwise, please hide it.

**Comment by chriskacerguis** [comment]
@chalettu per @Loicavenel comment here https://github.com/ManageIQ/manageiq-ui-service/issues/882#issuecomment-333203894 could you please investigate and use this if you can?

**Comment by Loicavenel** [comment]
There is a recent PR from Classic-UI for this

**Comment by chriskacerguis** [comment]
@Loicavenel this item is complete :)
