### ISSUE TITLE
icons not appearing on self service UI

### ISSUE THREAD

**Issue by jweewer** [ManageIQ/manageiq-ui-service#1036]
Description of problem:
After a custom skin is build and uploaded all the icons like the shoppingcart, notification icon, question mark, etc are missing from the interface.

How reproducible:
Just get the current code from github and build it with yarn.

Steps to Reproduce:
1.
2.
3.

Actual results:
no icons being in the navbar etc.

Expected results:
icons being in the navbar is expected

Additional info:

**Comment by AllenBW** [comment]
Confirmed, great catch @jweewer !!!
