### ISSUE TITLE
Provider and OS images via API

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1038]
In support of #910 but also all things, it would be super great if the api could serve provider and os images (by images, I mean the `.svg` that are generated and stored in `public/assets/svg`).  

* will ensure consistency of icons across uis
* will reduce bundle size of sui assets
* will be super cool

This discussion is kinda related but also kinda different: https://gitter.im/ManageIQ/manageiq/ui?at=59ce771f7b7d98d30d510fe2

@chriskacerguis

**Comment by chriskacerguis** [comment]
Will need this resolved: https://github.com/ManageIQ/manageiq-api/issues/92

**Comment by chriskacerguis** [comment]
@AllenBW good call on this.  @Loicavenel and @serenamarie125 are you on board with this too?

**Comment by Loicavenel** [comment]
Cannot comment on the technology side, but consistency is good.

**Comment by chriskacerguis** [comment]
Moving to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1502785
