### ISSUE TITLE
Create RBAC roles / features

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1054]
Per @Loicavenel [comment here](https://github.com/ManageIQ/manageiq-ui-service/pull/1053#issuecomment-333939715) we need to add RBAC to the following:

### Core
- [x] Application Launcher
- [ ] Switch Language

### Dashboard
- [ ] Monthly charge view

### My Services
- [ ] View / Show
- [ ] Start
- [ ] Stop
- [ ] Suspend
- [ ] Set Retirement Date
- [ ] Edit
- [ ] Remove
- [ ] Set Ownership

### VM Resource
- [ ] View Details
- [ ] View Snapshots
- [ ] Create Snapshot
- [ ] Delete Snapshot
- [ ] Open Remote Console
- [ ] Open Web Console
- [ ] Retire
- [ ] Start 
- [ ] Stop

### My Orders
- [ ]  View / Show
- [ ] Duplicate
- [ ] Modify
- [ ] Remove

### Service Catalog
- [ ] View / Show
- [ ] Add to Shopping Cart

### Shopping Cart
- [ ] View / Show
- [ ] Clear
- [ ] Order

**Comment by Loicavenel** [comment]
Just few points:
Core Can be renamed Top Menu or something else, I did not have better idea
This is missing the new stuff we are adding in 4.6.. 
We have to review VM resources here, it may be Resources with Sub Item like VM, Generic Object, Playbook etc... And for VM we can be granular on what we show: part of the dashboard for example

**Comment by AllenBW** [comment]
I wanta chime in here, been said before, will be said again, we should not add these roles to `product_features.yml` in manageiq until they are mapped to a behavior in the SUI, it would be dreadfully cruel and confusing to show users something that does nothing.

I propose twin prs, one in the sui that takes advantage of the feature, and another in manageiq that adds the feature.  Never one without the other 😆

**Comment by chriskacerguis** [comment]
@AllenBW totally agree.

**Comment by Loicavenel** [comment]
@AllenBW @chriskacerguis my goal was not asking to implement role but to make sure we have a clear list.. And yes, we should implement it feature after feature. I hope we can have it in Errata.

**Comment by chriskacerguis** [comment]
@Loicavenel understood.

**Comment by chalettu** [comment]
@miq-bot add_label wip

**Comment by Loicavenel** [comment]
@chalettu we need to organise it better and follow what was done already exist to don't confuse Customers


Self Service
	Core
		Application Launcher
		Switch Language
       Dashboard
		Monthly charge view
      My Services
		View
			Show
               Operate
			Start
                        Stop
			Suspend
 			Edit Tags
    			Set Retirement Date
			Retire Service
		Modify
			Edit
                        Remove
			Set OwnerShip
	VM Resources 
		View
			Details
			Snapshot
                Operate
                      Create Snapshots
                      Delete All Snapshots
                      Open Remote Console
		      Open Web Console
		      Edit Tag
		      Retire							
                      Stop
		      Start
	My Orders
		View
	              Show
                Operate 
                      Duplicate
		      Modify
                     Remove
 	 Service Catalog
		View
			Show
		Operate
			Add to Shopping Cart
	Shopping Cart
		View
			Show
		Operate
			Clear
			Order

**Comment by AllenBW** [comment]
@Loicavenel wanta confirm, use of `Self Service` should be `Service`?  (first item in your list)

**Comment by AllenBW** [comment]
Also Think we should rename ` Delete All Snapshots` to  `Delete Snapshots`, deleting all or a single one can both be wrapped up in that permission... 

Ok quick question... we have `Remove` For Orders, Services but `Delete` for Snapshots and `Clear` for the shopping cart... Thoughts on clearing up the  wording inconsistencies  around deleting things from places?

**Comment by Loicavenel** [comment]
Guys, sorry for the formatting here.. I thought Github will keep it..
All in the doc here. https://docs.google.com/document/d/10p69nnTT7dG0hnCBCJkcapjlxVd08J0A2QRX054B_08/edit

**Comment by chalettu** [comment]
@Loicavenel , can you post the finalized structure of permissions you would like to appear in the Classic UI?

**Comment by Loicavenel** [comment]
@chalettu It is in the Doc, I not sure or to post it in Github.. in which format

**Comment by chalettu** [comment]
<img width="800" alt="rbac1" src="https://user-images.githubusercontent.com/230549/31459975-1197269e-ae82-11e7-855c-11c583120e42.png">
<img width="466" alt="rbac_2" src="https://user-images.githubusercontent.com/230549/31459976-1323f226-ae82-11e7-9a50-35e30a3ed7a9.png">
<img width="357" alt="rbac_3" src="https://user-images.githubusercontent.com/230549/31459977-1492dc08-ae82-11e7-8926-c6676382bf02.png">
Here is the structure I have implemented.  I had to split it into 3 images so I could expand the structure

**Comment by chalettu** [comment]
@miq-bot remove_label wip

**Comment by chriskacerguis** [comment]
merged.

**Comment by chriskacerguis** [comment]
https://github.com/ManageIQ/manageiq-ui-service/pull/1090
