### ISSUE TITLE
GET /api/settings/api/max_results_per_page should inform the upper limit of all ui pagination 

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1122]
Implement the fix yielded by https://github.com/ManageIQ/manageiq-api/issues/136

Present state: we have some number hanging out, the case where this setting is lower than those numbers, user will be sad

Desired state: user is bound by this value for all pagination

**Comment by chriskacerguis** [comment]
Moved to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1514078
