### ISSUE TITLE
Apply standard styles to .spec.js files, add done() to async tests

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1127]
https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors

**Comment by chriskacerguis** [comment]
@AllenBW is this done?

**Comment by AllenBW** [comment]
yeah woops, referenced wrong issue in pr, 

closed by #1130
