### ISSUE TITLE
Beware of libraries that assert on property access, augment chai with dirty-chai

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1129]
https://github.com/moll/js-must#asserting-on-property-access

https://www.npmjs.com/package/dirty-chai

https://github.com/standard/standard/issues/690#issuecomment-278533482

**Comment by chriskacerguis** [comment]
Not 100% sure what the issue is here.  Going to close this, please open a BZ if needed.
