### ISSUE TITLE
[WIP] Migrate functionality for LoadUser to use Redux

### ISSUE THREAD

**Issue by chalettu** [ManageIQ/manageiq-ui-service#1134]
Move all functionality related to a user into its own service and remove it from Session Factory
Set this use redux to store user data between page reloads

**Comment by chalettu** [comment]
@miq-bot add_label technical debt
@miq-bot assign chalettu
@miq-bot add_label wip

**Comment by chriskacerguis** [comment]
Tracking in a single issue: https://github.com/ManageIQ/manageiq-ui-service/issues/1144
