### ISSUE TITLE
Migrate functionality to set language to utilize Redux

### ISSUE THREAD

**Issue by chalettu** [ManageIQ/manageiq-ui-service#1135]
Update how we persist selected language to use Redux.  This needs to change in such a way that removes this notion of having to set language on page reload.  Language factory should support retrieving selected language from redux when requested.  This means deprecating Language.onReload(response)

**Comment by chriskacerguis** [comment]
Closing Tracking here: https://github.com/ManageIQ/manageiq-ui-service/issues/1144
