### ISSUE TITLE
Look into compressing assets

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1141]
We should look into compressing assets, perhaps something like this:

https://github.com/theforeman/foreman/blob/develop/config/webpack.config.js#L133

**Comment by AllenBW** [comment]
So this would make sense if we were intent on serving compressed versions of assets with Content-Encoding, but this work will be more than adding the webpack plugin, need to reconfigure the way the apache server offers up the sui... a discussion that should include mo than sui peeps 

related...
https://stackoverflow.com/questions/11641923/transfer-encoding-gzip-vs-content-encoding-gzip#11664307

@ohadlevy @Fryguy, thoughts?

**Comment by chriskacerguis** [comment]
@ohadlevy @Fryguy, what do you all think?
