### ISSUE TITLE
Set 10 as the default for all list views

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1147]
Set 10 as the default for all list views

**Comment by ohadlevy** [comment]
Just a bit of context: during a quick demo today we've noticed that by default a user gets a scroll bar (e.g. there are items that do not show on your page and that you have to scroll) I think it make sense that the default page size does not load extra data that is not initially visibly, especially with regard to the fact some of these pages are slow to load to begin with. /cc @serenamarie125 @Loicavenel

**Comment by Loicavenel** [comment]
@chriskacerguis @ohadlevy can we get screenshots

**Comment by AllenBW** [comment]
<img width="1551" alt="screen shot 2017-10-25 at 11 07 17 am" src="https://user-images.githubusercontent.com/6640236/32006382-b2fc5d0e-b974-11e7-9ef7-5d1438488441.png">


vertical height of some 1200 px?

**Comment by Loicavenel** [comment]
Ok, so here we want to show only 10 items as default to avoid scroll bar...

**Comment by Loicavenel** [comment]
Just tried it... With 10 Items I still have a Scroll bar

**Comment by AllenBW** [comment]
<img width="1548" alt="screen shot 2017-10-25 at 11 28 35 am" src="https://user-images.githubusercontent.com/6640236/32007484-ad7b4ebe-b977-11e7-9f6a-371504f65fd5.png">

different resolution screens will behave, differently...

by default, we list the most recently created services first and all filtering is done on the whole collection (ie not just what you see on the screen) if we wanted to ensure more users didn't  have to scroll by default could use 5 as the default...  but this could grow tedious for some users who have large screens, are tired of clicking show more...

Furthermore, sui doesn't have a default settings section, which might not be a bad idea, allow the user to specify how many services orders or service catalogs they want to see by default

**Comment by Loicavenel** [comment]
I have a MacBook retina Display which I will consider a good resolution already. I can see 8 Services Total

**Comment by AllenBW** [comment]
Oh! wasn't trying to say your resolution was poor, if i set my display to macbook default, 1440 by 900 we see
<img width="1162" alt="screen shot 2017-10-25 at 11 36 43 am" src="https://user-images.githubusercontent.com/6640236/32007926-e83335ac-b978-11e7-8fa5-d57947176cd0.png">

Resolution my ss above was taken at is same display, resolution 1900 by 1200

**Comment by Loicavenel** [comment]
My point is even with 10 items you may still have a scroll bar, this does not remove the issue...

**Comment by chriskacerguis** [comment]
@Loicavenel My thought is that, but limiting the results, we limit the workload on the API.

**Comment by Loicavenel** [comment]
ok, at the end customer can change it after first page loaded

**Comment by chriskacerguis** [comment]
@Loicavenel Allen is going to post the load times at 10 vs 20.  Let's use that data to determine if this is worth doing :)

**Comment by serenamarie125** [comment]
This is very confusing to me.  We are limiting the page size so that there is no scrolling?  My opinion is that will anger customers more ... no one every wants to see just 10 items at a time

**Comment by AllenBW** [comment]
@serenamarie125 this is changing the default view to 10 (vs 20 it is set at presently) users will still be able to change that limit if they so choose...

for posterity, timing and additional discussion is now happening in this pr https://github.com/ManageIQ/manageiq-ui-service/pull/1155 ❤️

**Comment by serenamarie125** [comment]
@AllenBW gracias, moving there now :D
