### ISSUE TITLE
Kebab menu on list view items in My Services is not always visible

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1170]
Description of problem:

In My Services, if you access the kebab menu in the first couple of rows, it is hidden under the toolbar
Screenshot:

<img width="1183" alt="screen shot 2017-10-26 at 11 04 58 am" src="https://user-images.githubusercontent.com/12504403/32068428-538d1a8a-ba54-11e7-8ae5-a32a7753523e.png">

**Comment by serenamarie125** [comment]
@Loicavenel @AllenBW as discussed in our meeting 2017-Oct-26

**Comment by AllenBW** [comment]
I have a hunch this might be a pf-ang thing... i seem to remember this being a pf-ang... lower priority than the others, (unless otherwise instructed)

**Comment by chriskacerguis** [comment]
Move to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1514080
