### ISSUE TITLE
When looking at a service, the Resource action buttons should be on the same "row" as the rest of the information

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1171]
Description of problem:
When looking at a service, the Resource action buttons should be on the same "row" as the rest of the information

See the attached screenshot with issue:
<img width="1184" alt="screen shot 2017-10-26 at 11 05 50 am" src="https://user-images.githubusercontent.com/12504403/32068663-cde496f0-ba54-11e7-9696-4c731f8b61c7.png">

@Loicavenel @AllenBW as discussed in our meeting on 2017-Oct-26

**Comment by AllenBW** [comment]
This is an sui thing, we could/should be using menu buttons/ action buttons, (at the time of creation not part of pf-ang)  will do this first-ish (because i already started on it) unless otherwise instructed
