### ISSUE TITLE
Visual cleanup of Resource Detail View

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1176]
Description of problem:
Various items re: visual cleanup of the Resource Detail View
1. Toolbar should have a white background, be 60px high, and there should be a 20px margin before the beginning of the breadcrumb
2. There should be a 20 px left an right margin on the dashboard page
3. Can we have 2 columns when there are > 6 items on the Smart State Analysis card?
4. Per Smart state analysis, Icon should be 16 pt, Number 16 pt, and label 14 pt

Screenshot with callouts in red below:
![vmdetails_final](https://user-images.githubusercontent.com/12504403/32084889-d2756934-ba99-11e7-98e6-241574df7549.png)

fyi @Loicavenel @AllenBW

**Comment by chriskacerguis** [comment]
Closing.  Moved to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1514069
