### ISSUE TITLE
Service Details - spacing between buttons needs to be consistent

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1177]
Description of problem:

The spacing between buttons on the service details page is inconsistent.  

Please see the red arrow on the attached screenshot indicating 3 different margin values being used
![spacingbetweenbuttons](https://user-images.githubusercontent.com/12504403/32084947-3ac8ded0-ba9a-11e7-9126-84668d24067d.png)

FYI @AllenBW @Loicavenel

**Comment by chriskacerguis** [comment]
Closing.  Tracking via BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1507074
