### ISSUE TITLE
Inline notifications used on the login screen should match PatternFly

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1242]
Description of problem:
The visualization of the inline notification used on the login screen don't match PatternFly.  The screenshot below is from CloudForms Self Service 4.5:

How reproducible:
Every time

Steps to Reproduce:
1. Enter invalid username/password combination

Actual results:
<img width="689" alt="screen shot 2017-11-15 at 4 05 36 pm" src="https://user-images.githubusercontent.com/12504403/32845192-cff8668c-ca2c-11e7-9d46-52ab0b2beb79.png">

Expected results:
The PatternFly design can be found here: 
http://www.patternfly.org/pattern-library/application-framework/login-page/#/design

**Comment by ohadlevy** [comment]
related to https://github.com/patternfly/patternfly/issues/804

**Comment by AllenBW** [comment]
I am little 😕 ... the screen shot above is of the the ops ui... but the issue is posted in the SUI? anywho including a ss of the sui below..

<img width="1525" alt="screen shot 2017-11-15 at 9 32 45 am" src="https://user-images.githubusercontent.com/6640236/32841314-f5cc543a-c9e7-11e7-97dd-620b6b413420.png">

From the screen shot of sui current state, comparing to patternfly design, looking to understand what changes this issue is really asking for... gonna list it out.. cuz that seems logical 🤷‍♀️ 
* removal of language selection dropdonw
* addition of update password thingy
* addition of `region` `zone` and `appliance` text on the right
* addition of ® to Red Hat
* reduced spacing between login fields and product title
* addition of that lil' transparent bar thingy around the login field area

**Comment by AllenBW** [comment]
Okie dokie, ignoring my list, ON THIS ISSUE ! 👍 will have the change in, in a few shakes

**Comment by serenamarie125** [comment]
Sorry bout that @AllenBW messed up my screenshots!  I entered against both!

**Comment by AllenBW** [comment]
<img width="1048" alt="screen shot 2017-11-15 at 12 05 18 pm" src="https://user-images.githubusercontent.com/6640236/32849881-763fb31c-c9fe-11e7-8a7d-191a70f1e1e5.png">
@serenamarie125 notifications going alllll the way!  not gonna lie it kinda looks oddish thou...

<img width="1783" alt="screen shot 2017-11-15 at 12 14 46 pm" src="https://user-images.githubusercontent.com/6640236/32849950-adcccfe0-c9fe-11e7-9c39-40d7704dd8b5.png">

**Comment by AllenBW** [comment]
Ewww ok... working on a few related styling issues, cleanup up this file... hasn't been really touched in a while... stand by...

**Comment by serenamarie125** [comment]
@AllenBW i commented on the PR 
The issue was that the visualization ( colors ) of the inline notifications are wrong
The width was fine, as it matched the width of the content in the form.  In the PF case, there is more content, and the notification spans that content width.

**Comment by serenamarie125** [comment]
@AllenBW note the colors of the inline notification from PatternFly ... here's an image
![image](https://user-images.githubusercontent.com/12504403/32883009-c8e44ad6-cabe-11e7-9837-3d46b28116ae.png)

**Comment by AllenBW** [comment]
@serenamarie125 OH! that wasn't made clear in the original ask, I'll work on that today, where do we stand on the width of the notification? pre the per, they did in fact, not match patternfly.

So keep them as originally created, half width, or as the pr changes, full width?

**Comment by serenamarie125** [comment]
@AllenBW, i suggest half width as originally created, as it spanned the width of the content on your login screen.

My bad, when i said "visualization" I was referring to the colors, but I didn't specify that. Sorry!

**Comment by AllenBW** [comment]
@serenamarie125 no worries, all the cleanup that got us to full screen makes it easyish to go back, will update the pr to this effect
<img width="1000" alt="screen shot 2017-11-16 at 7 34 29 am" src="https://user-images.githubusercontent.com/6640236/32891485-b09285c4-caa0-11e7-81ca-764cf32e5dfb.png">
