### ISSUE TITLE
Language selector included on the login screen should match PatternFly

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#1243]
Description of problem:
There are a couple of gaps with the login screen:
1.  The language selector included on the login screen should match PatternFly.  The Username, Password and Language inputs should be the same width, and the Log In button should be on a separate line.
1. The product name font is incorrect

How reproducible:
Always on 4.5

Steps to Reproduce:
Bring up the login screen.

Actual results:
<img width="689" alt="screen shot 2017-11-15 at 4 05 36 pm" src="https://user-images.githubusercontent.com/12504403/32841074-1b974a64-ca22-11e7-8aae-1e28796cb559.png">

Expected results:
<img width="494" alt="screen shot 2017-11-15 at 4 19 27 pm" src="https://user-images.githubusercontent.com/12504403/32841090-2341c58c-ca22-11e7-8eaa-960ee6636ee8.png">

**Comment by AllenBW** [comment]
ON THIS!! 👍

**Comment by AllenBW** [comment]
Need to confirm a thing real quick. SUI is using http://www.patternfly.org/angular-patternfly/#/api/patternfly.select.component:pfSelect

Mocks appear to use http://www.patternfly.org/angular-patternfly/#/api/patternfly.select.directive:pfBootstrapSelect

but pattenfly says to use https://www.patternfly.org/pattern-library/widgets/#dropdowns (which matches the former, the in place flavor of select)

So we can do this: 
<img width="1047" alt="screen shot 2017-11-15 at 11 27 39 am" src="https://user-images.githubusercontent.com/6640236/32847483-1bb13dcc-c9f8-11e7-8dd2-60bd548fe6f0.png">

or this
<img width="1049" alt="screen shot 2017-11-15 at 11 27 02 am" src="https://user-images.githubusercontent.com/6640236/32847484-1bbb1ba8-c9f8-11e7-945e-166b10ef965e.png">

but looking at http://www.patternfly.org/pattern-library/application-framework/login-page/#/design it doesn't speak either way to a dropdown :-/

and the expected results appear to diverge from patternfly guidance on what type of dropdown to use...

It makes me no mind which direction but need explicit guidance from somewhere: @serenamarie125 @ohadlevy @chriskacerguis
