### ISSUE TITLE
Action button placement in provision dialog

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq-ui-service#1377]
**Description of problem:**

The position of _Add to shopping cart_ button ([details.html](https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/app/states/catalogs/details/details.html#L32-L42)) in a provision dialog in SSUI seems wrong to me:

![screenshot-2018-2-1 manageiq service template details](https://user-images.githubusercontent.com/1187051/35680228-08cb01b2-075a-11e8-9c74-05ff536c2a09.png)

I thought that the dialog is just a preview, and that adding to the cart will get me to the actual provision dialog. I'd prefer the button to be at the bottom to indicate that the dialog needs to be filled first and keep the workflow from the top to the bottom.

**Steps to Reproduce:**

1. go to Service Catalog
2. select a service

**Actual results:**

The button is on the top

**Expected results:**

The button is at the bottom

**Comment by romanblanco** [comment]
@serenamarie125 what do you think? Is this OK?

**Comment by serenamarie125** [comment]
Given that this is embedded in a page, yes!

The buttons should be on the bottom left.  I'm assuming we should also have a cancel button?

If so, left most button should be "Add to Shopping Cart" followed by "Cancel"
I'd also assume that the Add to Shopping Cart button would be blue

Thoughts @romanblanco ?

**Comment by romanblanco** [comment]
@serenamarie125 Thank you for the answer!

> The buttons should be on the bottom left. I'm assuming we should also have a cancel button?

There is a way to go back, but I agree having "Cancel" button would be better 

> I'd also assume that the Add to Shopping Cart button would be blue

It is at the moment the dialog is correctly filled.

**Comment by romanblanco** [comment]
@miq-bot assign @romanblanco

**Comment by tjyang** [comment]
Hi @romanblanco
Having user to scroll back just for submitting order is not convenient. 
Got a chance to work on remaining  "Cancel" button ?
