### ISSUE TITLE
Need help on changing support_website and support_website_text string

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-ui-service#1400]
Description of problem:
I am able to change the logo to my custom image by following [skin-simple readme](https://github.com/ManageIQ/manageiq-ui-service/tree/master/skin-sample)

But I want o customize both support_website and support_website_text string also.

How reproducible:

Steps to Reproduce:
1. skin.js
 From peeking at https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/app/core/appliance-info.service.spec.js
I came up with following skin.js
```
[root@miqr2wk01 skin-test]# pwd
/opt/manageiq/manageiq-ui-service/skin-moto
[root@miqr2wk01 skin-test]#

[root@miqr2wk01 skin-moto]# more skin.js
(function() {
  'use strict';

  var text = {
    app: {
      name: 'Test ManageIQ Service UI', // app name
    },
    login: {
      brand: 'Test  VM Self-Service Catalog ', // login screen
    },
    applianceInfoData: { 
     product_info: {
      'support_website': 'http://test.com/issues', // Using
      'support_website_text': 'Test  ManageIQ Support'
     },
    },
  };
  angular.module('app.skin', [])
    .constant('Text', text)
    .config(configure);

  /** @ngInject */
  function configure(routerHelperProvider, exceptionHandlerProvider) {
    exceptionHandlerProvider.configure('[SUI] '); // error prefix
    routerHelperProvider.configure({docTitle: 'Lenovo ManageIQ Service UI: '}); // page title
  }
})();


2. rebuild

``
cd /opt/manageiq/manageiq-ui-service;yarn build

<snipped>
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js?importLoaders=1&sourceMap=true!../node_modules/sass-loader/lib/loader.js??ref--5-3!assets/sass/styles.sass:
     66 assets
      [14] ../node_modules/css-loader?importLoaders=1&sourceMap=true!../node_modules/sass-loader/lib/loader.js?{"data":"$img-base-path: '/ui/service/'","sourceMap":true,"includePaths":["/opt/manageiq/manageiq-ui-service/client/assets/sass","/opt/manageiq/manageiq-ui-service/node_modules/bootstrap-sass/assets/stylesheets","/opt/manageiq/manageiq-ui-service/node_modules/patternfly/dist/sass/patternfly","/opt/manageiq/manageiq-ui-service/node_modules/font-awesome/scss","/opt/manageiq/manageiq-ui-service/node_modules/@manageiq/font-fabulous/assets/stylesheets"]}!./assets/sass/styles.sass 1.9 MB {0} [built]
            factory:125ms building:5899ms = 6024ms
        + 81 hidden modules
Done in 124.65s.
[root@miqr2wk01 manageiq-ui-service]#

```

3.  login to /ui/sevice again to check the Site(square) icon

Actual results:

![image](https://user-images.githubusercontent.com/378638/37409317-0e6dc28a-276c-11e8-8efb-5ab30765eb49.png)

Expected results:
MangeIQ.org text got changed to "Test ManageIQ Support"

Additional info:

**Comment by tjyang** [comment]
@AllenBW 
*  I change the text in appliance-info.service.spec.js

```
[root@miqr2wk01 manageiq-ui-service]# git diff ./client/app/core/appliance-info.service.spec.js
diff --git a/client/app/core/appliance-info.service.spec.js b/client/app/core/appliance-info.service.spec.js
index f42601c..02dd902 100644
--- a/client/app/core/appliance-info.service.spec.js
+++ b/client/app/core/appliance-info.service.spec.js
@@ -3,8 +3,8 @@ describe('Appliance Info Service', () => {
   const applianceInfoData = {
     'product_info': {
       'copyright': 'Copyright (c) 2017 ManageIQ. Sponsored by Red Hat Inc.',
-      'support_website': 'http://www.manageiq.org',
-      'support_website_text': 'ManageIQ.org'
+      'support_website': 'http://mytest.com/issues',
+      'support_website_text': 'My MIQ Support'
     },
     'identity': {
       'name': 'Administrator',
[root@miqr2wk01 manageiq-ui-service]#

```
* The do "cd /opt/manageiq/manageiq-ui-service;yarn build"
*  The text in About icon still not changed.

**Comment by AllenBW** [comment]
anything `.spec.js` is a test file, sadly won't change anything 😭 

I believe the setting you are looking for is in the ops-ui under `Configuration` 

if yah scroll to the bottom yah should see something that looks like this: 
<img width="777" alt="screen shot 2018-03-15 at 4 45 39 pm" src="https://user-images.githubusercontent.com/6640236/37490225-650650bc-2870-11e8-8761-9ef24956388e.png">

**Comment by tjyang** [comment]
@AllenBW 

I located the "Custom Support URL" and make changes to it but it doesn't reflect to /ui/serivce GUI.
Do I need to restart evm or httpd ?

Also this doesn't make sense to me, since ui-classic and ui-service resides in different paths.

**Comment by AllenBW** [comment]
Yep!  SUI runs off the api served by the default server, which provides the support url and description (we get this info when yah log into the sui).  It isn't a skinable part. Ok ok so I directed you to the wrong custom support url.. ACTUALLY you to:

root region server -> help tab and you'll see something like this:
<img width="997" alt="screen shot 2018-03-16 at 7 43 55 am" src="https://user-images.githubusercontent.com/6640236/37519134-680bd2cc-28ee-11e8-929e-46c65786a6a4.png">

lemme know if that works for yah @tjyang

**Comment by tjyang** [comment]
@AllenBW, I think this is a bug, IMHO.

To rule out complexity of multi appliances in same region, I did the test on another gapri-2 with all-in-one roles on same appliance called wk04.
All the settings to set support URL won't past on to ui/service node.js program.
* [Changes in classic ui Help Menu under configuration, region setting.](https://user-images.githubusercontent.com/378638/37525996-544735d4-28fc-11e8-98ff-e01678f762ae.png)
* [Custom Support URL change.](https://user-images.githubusercontent.com/378638/37526086-85910a48-28fc-11e8-9178-59c082373383.png)

* Displayed. 
![image](https://user-images.githubusercontent.com/378638/37525931-23a9501a-28fc-11e8-82b6-ffdb7d595817.png)

**Comment by AllenBW** [comment]
@tjyang sui displays what it is provided, this is a bug for elsewhere, but before submitting I would clear your browser session storage and maybe restart the server...

ss of the source info...
<img width="886" alt="screen shot 2018-03-16 at 11 03 40 am" src="https://user-images.githubusercontent.com/6640236/37527987-c7601d58-2909-11e8-83f0-95e1a53d4cd7.png">

**Comment by tjyang** [comment]
@AllenBW 

This is what did from a fresh downloaded  Gapri-2 vmware image and also browse it from different computer.

* I did all the web page URL redirecting to https://www.cnn.com

* Classic-UI result

![image](https://user-images.githubusercontent.com/378638/37532950-8c002aaa-290e-11e8-8671-a0a899bba518.png)

* Service-UI result

![image](https://user-images.githubusercontent.com/378638/37533043-cbbe5bf8-290e-11e8-933d-12dd7990adfc.png)

**Comment by AllenBW** [comment]
@tjyang again, not an SUI issue as it correctly displays what it is supplied.. would recommend submitting an issue against https://github.com/ManageIQ/manageiq-api 

gonna close this for now, but please feel free to reference it in the future
