### ISSUE TITLE
Is Sites icon configurable item ? 

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-ui-service#1402]
Description of problem:

We have a need to not to show the icon back to classical UI from ui/service page.
Can this be a configurable item in a skin.js file ? 

How reproducible:

login into ui/service we will see Sites icon by default

Steps to Reproduce when trying to remove the 3rd icon from source code :

1. Login into UI/service MIQ instance.
2.  Edit the natvigation-controller.js with following changes.

```
[root@miqr2wk01 navigation]# git diff  navigation-controller.js
diff --git a/client/app/core/navigation/navigation-controller.js b/client/app/core/navigation/navigation-controller.js
index 0b7a8d3..8fea80f 100644
--- a/client/app/core/navigation/navigation-controller.js
+++ b/client/app/core/navigation/navigation-controller.js
@@ -65,7 +65,7 @@ export function NavigationController (Text, Navigation, Session, API_BASE, Shopp
       markAllRead: markAllRead,
       shoppingCart: shoppingCart(),
       about: about(),
-      sites: sites()
+//      sites: sites()
     })
     setupNavigation()
     refresh()
@@ -118,14 +118,14 @@ export function NavigationController (Text, Navigation, Session, API_BASE, Shopp
     }
   }

-  function sites () {
-    return [{
-      title: __('Administration UI'),
-      tooltip: __('Log into the full administrative UI'),
-      iconClass: 'fa-cogs',
-      url: API_BASE
-    }]
-  }
+//  function sites () {
+//    return [{
+//      title: __('Administration UI'),
+//      tooltip: __('Log into the full administrative UI'),
+//      iconClass: 'fa-cogs',
+//      url: API_BASE
+//    }]
+//  }

   function clearActiveItems () {
     angular.forEach(vm.items, function (item) {
[root@miqr2wk01 navigation]#
```
3. Rebuild after above code change.

```
#cd /opt/manageiq/manageiq-ui-service;yarn build
```

Actual results:
![image](https://user-images.githubusercontent.com/378638/37414013-377d7e4a-2776-11e8-8d3d-064c3610f581.png)

Expected results:

Above code change doesn't remove the icon.
Site icon(3rd from the left) disappeared.

Additional info:

**Comment by himdel** [comment]
```
$ ag sites
client/app/layouts/application.html
44:          <miq-site-switcher sites="vm.sites" ng-if="vm.permissions.suiAppLauncher"></miq-site-switcher>
```

So .. looks like simply removing the `suiAppLauncher` permission already accomplishes this.

`suiAppLauncher` is an alias for `RBAC.has(RBAC.FEATURES.CORE.APP_LAUNCHER)`,
which is a random constant for `"APP_LAUNCHER": "sui_app_launcher",`.

Thus, not giving the user a permission to `sui_app_launcher` should solve this.

(This should be Service UI > Core > Application Launcher in the UI.)
