### ISSUE TITLE
Language pull down menu should be in Header ?

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-ui-service#1403]
Description of problem:

Current "Language" pull own is below "Password" row, It is creating in-convenience since the pull down menu only display 4 languages option at most. 

How reproducible:
visit miq's ui/service link

Steps to Reproduce:
This is on Gapri-2
1. Click on "User Default" button to see the pull down list of Language choice
2.  We have to switch to use up down key in keyboard to navigate complete choice.
3.  Right scroll-bar can't scroll down see all the choice.

Actual results:
![image](https://user-images.githubusercontent.com/378638/37419020-89ef2272-2781-11e8-868e-fc15f92b7cd2.png)

Expected results:

Won't it be better move "Language" 
" to top left or right corner to display the max height of a browser body ?

Additional info:
Something like this 

![image](https://user-images.githubusercontent.com/378638/37422801-1ca304aa-278a-11e8-92d8-e47764460706.png)

**Comment by himdel** [comment]
Not on the login screen.

However, we can add `dropupAuto: true` so that the list expands upwards instead of down
