### ISSUE TITLE
non-admin user can't get to "VM Console"

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-ui-service#1404]
Description of problem:

As non admin user, user should be able to get to noVNC webconsole of their running services(VM) like admin user login ui/service did.

Steps to Reproduce:
1.  login miq ui/service as regular user
2.  My Services -> [Select a running service with Green check mark.](https://user-images.githubusercontent.com/378638/37420015-cfc346a0-2783-11e8-84bb-7b639c70029d.png)
3. From Access pull down , [click on VM Console.](https://user-images.githubusercontent.com/378638/37420106-fcb45ea6-2783-11e8-9fcd-3c31d1aa0127.png)

Actual results:

We see error message saying ["There was an error opening the console. undefined"](https://user-images.githubusercontent.com/378638/37419757-2c6f9e0e-2783-11e8-92f8-77c2354a32fa.png)

Additional info:

Not sure what to grep on error in /var/www/miq/vmdb/log/api.log

**Comment by easyljy** [comment]
add roles as below
![image](https://user-images.githubusercontent.com/10966153/37684353-c3c7d544-2c5d-11e8-95ad-6605abeee437.png)
