### ISSUE TITLE
Wrong "Order" translation for Chinese.

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-ui-service#1405]
Description of problem:

Wrong Chinese "Order" translation when it is a verb.

https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/gettext/po/zh-Hans-CN/manageiq-ui-service.po#L719

How reproducible:

Switch to Chinese language on Windows 10.

Steps to Reproduce:
1. order in noun form is 订单
2. order in verb form is  订购

Actual results:

![image](https://user-images.githubusercontent.com/378638/37427412-666d2f90-2797-11e8-8dd9-1479e0e524a1.png)

Expected results:

"Order" button should be translated to  “订购” , not “订单” in blue.

Additional info:

Please advise me the procedure the update the .po file and have it populated to new ui/service code.
My following two lines effort was not working.

```
1. [edit .po file](https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/gettext/po/zh-Hans-CN/manageiq-ui-service.po#L719) with correct Chinese translation. 
2.  cd /opt/manageiq/manageiq-ui-service;yarn build
```

**Comment by AllenBW** [comment]
closing as per conversation :point_right: [March 15, 2018 8:57 AM](https://gitter.im/ManageIQ/manageiq-ui-service?at=5aaa6dc9012ff2bf681d869c)
