### ISSUE TITLE
Migration requests are appearing in My Order of SSUI

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1463]
https://bugzilla.redhat.com/show_bug.cgi?id=1565049

Migration requests are showing in 'My Order' of SSUI, but the SUI doesn't have a means of filtering service orders by type yet, which is why the work described in this issue is dependent on https://github.com/ManageIQ/manageiq/issues/17752

https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/341#issuecomment-405234756

🌮 🤗

**Comment by himdel** [comment]
@miq-bot remove_label stale

This is still relevant,
depdens on https://github.com/ManageIQ/manageiq-schema/pull/328

**Comment by himdel** [comment]
Waiting for https://github.com/ManageIQ/manageiq-schema/pull/328 
Looks like it's clear we're going the STI direction - we'll be filtering by the service order type column.

**Comment by himdel** [comment]
OK, looks like backend is merged, we now have 2 different kinds of ServiceOrder: `ServiceOrderCart` and `ServiceOrderV2V`.
Therefore the SUI can now filter by `type`.
