### ISSUE TITLE
SUI to support support webmks 

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1520]
Description of problem:
:point_up: [January 29, 2019 9:51 AM](https://gitter.im/ManageIQ/manageiq/providers?at=5c5068888aa5ca5abf4edda7)

https://bugzilla.redhat.com/show_bug.cgi?id=1532720

**Comment by skateman** [comment]
So as the WebMKS console isn't shipped OOTB and we cannot precompile assets on an already existing appliance, it cannot be included into the asset pipeline nor a webpack pack (sounds funny, you seriously say it like this?). So I think we could do the following:
```js
// Send a HEAD request to determine if the file exists, IMO it's enough to check for the JS
fetch('webmks/wmks.min.js', {
  method: 'HEAD'
}).then(() => new Promise((resolve, reject) => { // Create and return with a promise
  // Create a <link> tag that loads the CSS file and append it to the page
  let link = document.createElement('link');
  link.rel = 'stylesheet';
  link.type = 'text/css';
  link.href = '/webmks/css/wmks-all.css';
  document.head.appendChild(link);

  // Create a <script> tag that loads the JS file
  let script = document.createElement('script');
  script.src = '/webmks/wmks.min.js';

  script.onload = () => resolve(); // Set an onload function that resolves the promise

  document.head.appendChild(script); // Append the <script> tag to the page
})).then(() => {
  // The code is loaded, we can do stuff with WebMKS
}).catch((error) => {
  // some error handling
});

```

**Comment by himdel** [comment]
I suppose so..., which implementation of `fetch`?

**Comment by ahrechushkin** [comment]
Is there any new about this feature?

**Comment by skateman** [comment]
@AllenBW when will you have time to take a look? Do you have any questions about how and where to start?

**Comment by AllenBW** [comment]
Heyoh pto caused the delayed response, if time is available later this week I can begin to give this some 👀 in earnest! 🤞

**Comment by ahrechushkin** [comment]
up

**Comment by skateman** [comment]
@AllenBW ping?

**Comment by AllenBW** [comment]
Yah, haven't had the time. 😔

**Comment by ahrechushkin** [comment]
up

**Comment by AllenBW** [comment]
no update on my end

**Comment by skateman** [comment]
Yes update on my end, final PR coming soon :smiling_imp:
