### ISSUE TITLE
About screen "SUI Version" is empty in container build

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-ui-service#1634]
In container image build, source is downloaded as a tarball ahead of time and there is no .git directory. This causes "SUI Version" to be empty in About screen.

Is it possible to look for a file existence and use value from there if exists (which is how OpsUI works), rather than always calling `git rev-parse`?

**Comment by h-kataria** [comment]
@himdel can you take a look

**Comment by himdel** [comment]
How this works is that `yarn run build` calls  `yarn run build:git-hash`, which creates `client/version/version.json` with the right commit info.

```
$ cat client/version/version.json
{"gitCommit": "158f2bf5948f9ce0b34fba42e4a8a24295d6a28e"}
```

As long as `client/version/version.json` exists, that's where SUI takes the version from.
So, if you're building from a tarball, you will need to provide the built `client/version/version.json` manually.

Looks like the task doesn't fail without git, it just generates a file with empty `gitCommit`, so the only thing that needs to happen is replacing the file afterwards.

**Comment by simaishi** [comment]
> As long as `client/version/version.json` exists, that's where SUI takes the version from.
> So, if you're building from a tarball, you will need to provide the built `client/version/version.json` manually.

That's how I started, and realized `yarn run build:git-hash` will overwrite it...

> Looks like the task doesn't fail without git, it just generates a file with empty `gitCommit`, so the only thing that needs to happen is replacing the file after the build.

To do that, we have to pass SHA in some way. So I thought if we're generating a file for that purpose, maybe SUI can read that file instead at build time. If not, I'll do what you suggested.

**Comment by himdel** [comment]
Well, if you already have some magic file present for all the builds, we can use that, sure.

But the file won't be around for any other builds, so `config/githash.js` still needs to do the right thing without it.

**Comment by simaishi** [comment]
No, not for all builds... which is why I mentioned "if exists". OpsUI will look for `BUILD` file to get SHA and if it doesn't exist, it will use `git rev-parse`, so I thought maybe SUI can do something similar...

**Comment by himdel** [comment]
Sure, so, what are the details?

Where would the build find the file? Is it `manageiq-ui-service/BUILD` ?
And what's inside? Only the hash as a single line string?

**Comment by himdel** [comment]
Assuming `manageiq-ui-service/BUILD` and assuming it only contains the raw sha (and possibly a newline):

```
diff --git a/config/githash.js b/config/githash.js
index 754794c1..5bbd0b19 100644
--- a/config/githash.js
+++ b/config/githash.js
@@ -1,11 +1,15 @@
-const shell = require('shelljs')
-const fs = require('fs')
-const path = require('path')
-const filePath = path.join(__dirname, '../client/version/version.json')
-const gitCommit = shell.exec('git rev-parse HEAD', {silent: true}).stdout
-
-const gitFileContents = `{"gitCommit": "${gitCommit.replace("\n", '')}"}` // eslint-disable-line 
-fs.writeFile(filePath, gitFileContents, (err) => {
-  if (err) throw err
-  console.log(`Successfully wrote Git hash - ${gitCommit}`)
-})
+const { exec } = require('shelljs');
+const { existsSync, readFileSync, writeFileSync } = require('fs');
+const { join } = require('path');
+
+const input = join(__dirname, '../BUILD');
+const output = join(__dirname, '../client/version/version.json');
+
+let gitCommit = existsSync(input)
+  ? readFileSync(input, { encoding: 'utf-8' })
+  : exec('git rev-parse HEAD', { silent: true }).stdout;
+gitCommit = gitCommit.replace("\n", '');
+
+writeFileSync(output, JSON.stringify({ gitCommit }));
+
+console.log(`Successfully wrote Git hash - ${gitCommit}`);
```

**Comment by simaishi** [comment]
`BUILD` file with SHA works for me!

**Comment by himdel** [comment]
Great, fixing in https://github.com/ManageIQ/manageiq-ui-service/pull/1636 :)
