### ISSUE TITLE
Service UI should support Accessibility (a11y)

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-ui-service#1662]
Some background information on accessibility can be found at [w3.org](https://www.w3.org/WAI/fundamentals/accessibility-intro/), [a11yproject](https://www.a11yproject.com/) and [usability.gov](https://www.usability.gov/what-and-why/accessibility.html).  One can find a community-driven accessibility checklist [here](https://www.a11yproject.com/checklist/).

The following checklist is derived from the [IBM Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)

**Text Alternatives: Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language.**
- [ ] [Non-text Content](https://www.ibm.com/able/guidelines/ci162/non_text_content.html)

**Time-based Media: Provide alternatives for time-based media.**
- [ ] [Audio-only and Video-only (Prerecorded)](https://www.ibm.com/able/guidelines/ci162/audio_and_video.html)
- [ ] [Captions (Prerecorded)](https://www.ibm.com/able/guidelines/ci162/captions.html)
- [ ] [Audio Description or Media Alternative (Prerecorded)](https://www.ibm.com/able/guidelines/ci162/media_alternative.html)
- [ ] [Captions (Live)](https://www.ibm.com/able/guidelines/ci162/captions_live.html)
- [ ] [Audio Description (Prerecorded)](https://www.ibm.com/able/guidelines/ci162/media_alternative.html)

**Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure.**
- [ ] [Info and Relationships](https://www.ibm.com/able/guidelines/ci162/info_and_relationships.html)
- [ ] [Meaningful Sequence](https://www.ibm.com/able/guidelines/ci162/meaningful_sequence.html)
- [ ] [Sensory Characteristics](https://www.ibm.com/able/guidelines/ci162/sensory_characteristics.html)
- [ ] [Orientation](https://www.ibm.com/able/guidelines/ci162/orientation_71.html)
- [ ] [Identify Input Purpose](https://www.ibm.com/able/guidelines/ci162/identify_input_purpose_71.html)

**Distinguishable: Make it easier for users to see and hear content including separating foreground from background.**
- [ ] [Use of Color](https://www.ibm.com/able/guidelines/ci162/color.html)
- [ ] [Audio Control](https://www.ibm.com/able/guidelines/ci162/audio_control.html)
- [ ] [Contrast (Minimum)](https://www.ibm.com/able/guidelines/ci162/contrast.html)
- [ ] [Resize Text](https://www.ibm.com/able/guidelines/ci162/resize_text.html)
- [ ] [Images of Text](https://www.ibm.com/able/guidelines/ci162/images_of_text.html)
- [ ] [Reflow](https://www.ibm.com/able/guidelines/ci162/reflow_71.html)
- [ ] [Non-text Contrast](https://www.ibm.com/able/guidelines/ci162/non-text_contrast_71.html)
- [ ] [Text Spacing](https://www.ibm.com/able/guidelines/ci162/text_spacing_71.html)
- [ ] [Content on Hover or Focus](https://www.ibm.com/able/guidelines/ci162/content_on_hover_71.html)

**Keyboard Accessible: Make all functionality available from a keyboard.**
- [ ] [Keyboard](https://www.ibm.com/able/guidelines/ci162/keyboard.html)
- [ ] [No Keyboard Trap](https://www.ibm.com/able/guidelines/ci162/no_keyboard_trap.html)
- [ ] [Character Key Shortcuts](https://www.ibm.com/able/guidelines/ci162/character_key_shortcuts_71.html)

**Enough Time: Provide users enough time to read and use content.**
- [ ] [Timing Adjustable](https://www.ibm.com/able/guidelines/ci162/timing_adjustable.html)
- [ ] [Pause, Stop, Hide](https://www.ibm.com/able/guidelines/ci162/pause_stop_hide.html)

**Seizures: Do not design content in a way that is known to cause seizures.**
- [ ] [Three Flashes or Below Threshold](https://www.ibm.com/able/guidelines/ci162/blinking.html)

**Navigable: Provide ways to help users navigate, find content, and determine where they are.**
- [ ] [Bypass Blocks](https://www.ibm.com/able/guidelines/ci162/bypass_blocks.html)
- [ ] [Page Titled](https://www.ibm.com/able/guidelines/ci162/page_titled.html)
- [ ] [Focus Order](https://www.ibm.com/able/guidelines/ci162/focus_order.html)
- [ ] [Link Purpose (In Context)](https://www.ibm.com/able/guidelines/ci162/link_purpose.html)
- [ ] [Multiple Ways](https://www.ibm.com/able/guidelines/ci162/multiple_ways.html)
- [ ] [Headings and Labels](https://www.ibm.com/able/guidelines/ci162/headings_and_labels.html)
- [ ] [Focus Visible](https://www.ibm.com/able/guidelines/ci162/focus_visible.html)

**Input Modalities: Make it easier for users to operate functionality through various inputs beyond keyboard.**
- [ ] [Pointer Gestures](https://www.ibm.com/able/guidelines/ci162/pointer_gestures_71.html)
- [ ] [Pointer Cancellation](https://www.ibm.com/able/guidelines/ci162/pointer_cancellation_71.html)
- [ ] [Label in Name](https://www.ibm.com/able/guidelines/ci162/label_in_name_71.html)
- [ ] [Motion Actuation](https://www.ibm.com/able/guidelines/ci162/motion_actuation_71.html)

**Readable: Make text content readable and understandable.**
- [ ] [Language of Page](https://www.ibm.com/able/guidelines/ci162/language_of_page.html)
- [ ] [Language of Parts](https://www.ibm.com/able/guidelines/ci162/language_of_parts.html)

**Predictable: Make Web pages appear and operate in predictable ways.**
- [ ] [On Focus](https://www.ibm.com/able/guidelines/ci162/on_focus.html)
- [ ] [On Input](https://www.ibm.com/able/guidelines/ci162/on_input.html)
- [ ] [Consistent Navigation](https://www.ibm.com/able/guidelines/ci162/consistent_navigation.html)
- [ ] [Consistent Identification](https://www.ibm.com/able/guidelines/ci162/consistent_id.html)

**Input Assistance: Help users avoid and correct mistakes.**
- [ ] [Error Identification](https://www.ibm.com/able/guidelines/ci162/error_id.html)
- [ ] [Labels or Instructions](https://www.ibm.com/able/guidelines/ci162/labels_or_instructions.html)
- [ ] [Error Suggestion](https://www.ibm.com/able/guidelines/ci162/error_suggestion.html)
- [ ] [Error Prevention (Legal, Financial, Data)](https://www.ibm.com/able/guidelines/ci162/error_prevention.html)

**Compatible: Maximize compatibility with current and future user agents, including assistive technologies.**
- [ ] [Parsing](https://www.ibm.com/able/guidelines/ci162/parsing.html)
- [ ] [Name, Role, Value](https://www.ibm.com/able/guidelines/ci162/name_role_value.html)
- [ ] [Status Messages](https://www.ibm.com/able/guidelines/ci162/status_messages_71.html)
- [ ] [Accessibility-supported Technologies Only](https://www.ibm.com/able/guidelines/ci162/accessibility_supported_71.html)

**Comment by Fryguy** [comment]
Closing in favor of putting the UI on the Chopping Block https://github.com/ManageIQ/manageiq/issues/21377
