### ISSUE TITLE
Need a manifest generator similar to the one in classic ui.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-ui-service#1670]
@himdel Do you know what it would take to do this?

**Comment by bhadrim** [comment]
@himdel Can you also push the changes to Jansa? Thank you.

**Comment by himdel** [comment]
:+1: Added `jansa/yes?`

**Comment by bhadrim** [comment]
@Fryguy @himdel Than you for merging this to master but I do not see changes to https://github.com/ManageIQ/manageiq-ui-service/blob/jansa/config/webpack.prod.js yet. If you can merge these changes on Jansa, I can start my downstream build when it gets there. Thank you.

**Comment by Fryguy** [comment]
@bhadrim The label `jansa/yes?` is a request for backport, which the triage team will evaluate.  Once it's actually backported, it will change to `jansa/backported` .
