### ISSUE TITLE
prepare the development environment to make code changes

### ISSUE THREAD

**Issue by ismailostmar** [ManageIQ/manageiq-ui-service#1814]
Hello everyone, as part of the Manageiq project I am responsible for making changes to the service catalog by grouping the services created in a drop down menu to have a good user interface and easy to choose the services to create.

I am a Developer and I don't know how to prepare the development environment to make code changes, where can I start, i think that using an OVA is easy but still have no idea, i work alone, I searched on Documentation and I found to use an OVA Machine will be easier to prepare a development environment for Manageiq

I need some help please 🙏

**Comment by Fryguy** [comment]
Can yo give more details on what you're trying to accomplish?  It's hard to understand what exactly you're trying to solve.

**Comment by ismailostmar** [comment]
Hello everyone, as part of the Manageiq project I am responsible for making changes to the service catalog by grouping the services created in a drop down menu to have a good user interface and easy to choose the services to create.

I am a Developer and I don't know how to prepare the development environment to make code changes, where can I start, i think that using an OVA is easy but still have no idea, i work alone, I searched on Documentation and I found to use an OVA Machine will be easier to prepare a development environment for Manageiq

I need some help please 🙏

**Comment by Fryguy** [comment]
The docs for setting up the dev environment are here in this repo under https://github.com/ManageIQ/manageiq-ui-service/blob/master/docs/developer_setup.md.  For ManageIQ in general, please refer to the Developer Setup guide here: https://github.com/ManageIQ/guides/blob/master/developer_setup.md

**Comment by ismailostmar** [comment]
Yes indeed, I would just like to know how I'm going to prepare the Dev environment, as I'm working in a project with a freelance company, and I'm in charge of setting up an environment but I don't know where I'm starting from, what do you recommend as a trick whether it's an OVA machine already configured or a Docker container, Kubernetes...

**Comment by Fryguy** [comment]
The recommendation for development in the ManageIQ org is to use your local machine for development and follow the developer setup as documented.  I know there are some developers who like to develop on the appliance directly, but in our experience that makes development much more complicated.  There are docs for [developing in a vagrant VM](https://github.com/ManageIQ/guides/blob/master/vagrant_developer_vm.md), but I personally have never done that, so I cannot attest to how well it works or not.
