### ISSUE TITLE
Modals not closing on state transition

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-ui-service#24]
Opening a modal and waiting for the authentication token to expire eventually leads to a login screen with the modal still on top of that.

I want to patch `$modal` to be aware of `ui-router` state transitions and just cancel whenever one happens.

@miq-bot assign himdel

**Comment by himdel** [comment]
@romanblanco I created the issue, can you add the screenshot please?

**Comment by romanblanco** [comment]
Screenshot:

![screencapture-localhost-3001-self_service-login-1457509214322](https://cloud.githubusercontent.com/assets/1187051/13697642/12669fa4-e76f-11e5-8168-cc88bdba5444.png)

**Comment by chriskacerguis** [comment]
@himdel is this still an issue?

**Comment by himdel** [comment]
Yup it is. Transition caused by background requests failing with 404 will currently not close any open modal, nor can they really.

I'll be touching that code as part of the server error dialog (SSUI version of https://github.com/ManageIQ/manageiq/pull/10984), so planning to address that at that point by redirecting to the login screen instead of changing state to it.

**Comment by chriskacerguis** [comment]
@himdel any word on a fix here?

**Comment by himdel** [comment]
Oh, sorry, yup, still on my list.

But the fix will be to replace every `$state.go('login')` with essentially something like `document.href = '/ui/service';` (except ideally not hardcoded, etc.)

**Comment by chriskacerguis** [comment]
@himdel want me to assign this to someone else?

**Comment by himdel** [comment]
@chriskacerguis Up to you, but if you want this done fast, please do feel free to reassign :) (I'm on PTO next week..)

**Comment by chriskacerguis** [comment]
Moved here: https://www.pivotaltracker.com/story/show/134431669
