### ISSUE TITLE
Update gulp serve to start MIQ as well

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#259]
We need to update the gulp serve task to start MIQ start use the "rails s"

**Comment by chriskacerguis** [comment]
Thinking about what @himdel said.  I'm thinking we should revisit this.  Le's adjust gulp serve to NOT start MIQ, and instead let's add a new task that will start both.

**Comment by himdel** [comment]
Agreed, that makes sense :) Either that, or a way to disable the functionality, via some sort of ENV variable.. but I like a separate task even better :).

And.. the task should probably fail when spawning rails fails..

**Comment by AparnaKarve** [comment]
> but I like a separate task even better

I second that. A separate gulp task would be better. No confusion whatsoever.

**Comment by chalettu** [comment]
I resubmitted this as a new PR https://github.com/ManageIQ/manageiq-ui-service/pull/268.   Feel free to take a look.  It now is a separate gulp task and it accepts a ENV variable that will allow you to override the port that you start Manage IQ on.  I ran our ES Lint rules against the new file and corrected the issues it found. Please feel free to take a look at it.  Thank you all for your input.

**Comment by chriskacerguis** [comment]
#268 has been merged.
