### ISSUE TITLE
Need an API to get Compute, Network & Storage items for a provisioned service

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#262]
Currently, the Self Service UI is showing just the VMs, so there is an API which is returning that information.  We need APIs to get the information for compute resources, network resources and storage resources.

The above is needed to satisfy the following use case:  When I deploy a service, under My Services I would like my services to break down the items deployed into Compute, Network, Storage.

**Comment by serenamarie125** [comment]
@

**Comment by serenamarie125** [comment]
@jntullo can you look into this?

**Comment by chriskacerguis** [comment]
@jntulloNot 100% sure what we need here, can you please add additional issues and use this as a master list of issues?

**Comment by serenamarie125** [comment]
This is necessary for the My Service Headings that we discussed earlier in the week :)  @jntullo let me know if you need further clarification.

**Comment by chriskacerguis** [comment]
@serenamarie125 yup no worries there, just wanted to know the actual engineering tasks.

**Comment by jntullo** [comment]
will do @chriskacerguis

**Comment by jntullo** [comment]
You are able to get associated service resources via the `service_resources` attribute. 
Example call:
`/api/services/10000000000406?attributes=service_resources`
