### ISSUE TITLE
Add 508 compliance

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#273]
Need to add support for 508 compliance in the SUI.

**Comment by chriskacerguis** [comment]
@AllenBW do you remember where we found that doc on 508 compliance for Jellyfish?

**Comment by AllenBW** [comment]
eeeeeeeeek a checklist? http://www.hhs.gov/web/section-508/making-files-accessible/checklist/html/index.html

or a tester?  http://www.powermapper.com/products/sortsite/checks/accessibility-checks/

right off hand drawing ... ... ... ⬛️

**Comment by chriskacerguis** [comment]
Since this will no doubt affect UI things, I'm sending to @serenamarie125 for her and her team to review this.

**Comment by serenamarie125** [comment]
This is a scary one 👻  We are going through that effort with PatternFly now, so we should be able to take some cues from there!
