### ISSUE TITLE
Browsersync is not respecting other ports

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq-ui-service#28]
Noticed a strange thing when I was running two different forks of ManageIQ SSUI:

Forks were in separated folders, running in different ports and in different browser, but I was always able to view only the one running on default port `3001`.

Problem is probably caused by Browsersync, that keeps connecting to the same port
_(probably somewhere here:  [gulp/tasks/serve.js](https://github.com/ManageIQ/manageiq-ui-self_service/blob/master/gulp/tasks/serve.js))_

@himdel

**Comment by romanblanco** [comment]
@miq-bot assign himdel

**Comment by chriskacerguis** [comment]
@himdel can you please take a look here?

**Comment by chriskacerguis** [comment]
@himdel @romanblanco is this still an issue?

**Comment by himdel** [comment]
Still an issue, #44 only fixes websocket proxying, the issue that browsersync still always uses the port 8001 unless a `PORT` environment variable was provided, and always redirects to 3001 remains.

It's hardcoded in the config (`gulp/config.js` - grep for `browserSyncOptions`).

**Comment by chriskacerguis** [comment]
@himdel what's the word on a fix for this?

**Comment by himdel** [comment]
None so far, not really a priority for me.

**Comment by chriskacerguis** [comment]
@himdel ok, thanks.  I'll assign this to someone else.

**Comment by chriskacerguis** [comment]
@AllenBW can you please take a look here.

**Comment by AllenBW** [comment]
eeeeek @chriskacerguis, higher priority than removing bower?

**Comment by chriskacerguis** [comment]
@AllenBW bower, then this.

**Comment by chriskacerguis** [comment]
Moved here: https://www.pivotaltracker.com/story/show/134431583
