### ISSUE TITLE
Create 508 compliance scanner gulp task

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#280]
In support for https://github.com/ManageIQ/manageiq-ui-service/issues/273 we need to add a gulp task that can scan for compliance.

**Comment by chalettu** [comment]
So people know what I am looking into, I am experimenting with https://github.com/yargalot/gulp-accessibility to see if it could work well to help report on the 508 compliance of our codebase.

**Comment by chriskacerguis** [comment]
test comment.  ignore.

**Comment by chriskacerguis** [comment]
test commetn.
