### ISSUE TITLE
Service UI should have the same rebranding abilities as the Classic Ops UI

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#300]
There is a lot of chatter on cf-tech as well as from customers per this item.  The service UI should have the same rebranding abilities as the Classic Ops UI.

@chriskacerguis this should be assigned to me initially, and then I can get @dgutride tasked with addressing this, as he has looked into branding previously.  

@jonnyfiveiq once this is completed, you should determine how/where the fix should be placed, meaning should it be back ported.

@Loicavenel FYI

**Comment by chriskacerguis** [comment]
Yup, that's why I logged it.  That said, before any work is done, it needs to get prioritized, as l suspect it may need API work (no sense of spending resources doing UX if we don't have any for API).

**Comment by chriskacerguis** [comment]
Actually, closing this.  This is a dup of a previous ticket here:  https://github.com/ManageIQ/manageiq-ui-service/issues/274
