### ISSUE TITLE
Profile images not found

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-ui-service#316]
Hi, 
when creating a profile the image is not loading (404). The profile image is referenced as:
https://hostname/self_service/assets/images/providers/vendor-vmware_cloud.svg
is should be referenced as
https://hostname/self_service/images/providers/vendor-vmware_cloud.svg

without the assets.

I am testing on euwe-RC1.

**Comment by chriskacerguis** [comment]
@AllenBW can you take a look when you get a moment?

**Comment by AllenBW** [comment]
acknowledged and replicated, working on a fix presently, thanks for bringing this to light @evertmulder 🙇
