### ISSUE TITLE
Refactor vertical navigation to support dynamic translations and badge counts

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#328]
As identified https://github.com/ManageIQ/manageiq-ui-service/pull/327 [angular-patternfly](https://github.com/patternfly/angular-patternfly) doesn't quite [support translations](https://github.com/patternfly/angular-patternfly/issues/35#issuecomment-1343044070), so the appropriate values must be supplied. If we act on the original navigation list, the ability to go from a second language to a third language is lost. If we act on the original list and display the resultant copy, badge counts are only updated when languages are.  

The aforementioned pr addresses the issue by reloading the page, an undesired longterm fix. 

A pr that solves this issue will result in the ability to change third and fourth languages while maintaining current badge counts without refreshing the state.

@himdel (for posterity)

**Comment by himdel** [comment]
@chriskacerguis I think this one may need a pivotal story too...

**Comment by chriskacerguis** [comment]
Story here: https://www.pivotaltracker.com/story/show/134436111
