### ISSUE TITLE
When logged in as non-admin user, polling requests are made for forbidden resources

### ISSUE THREAD

**Issue by jjlangholtz** [ManageIQ/manageiq-ui-service#334]
If the currently authenticated user does not have authorization for certain product features (such as **arbitration profiles**, **service dialogs**, and **blueprints**) the application will still attempt to make requests for those forbidden resources.

To reproduce login as a user that does not have permissions for the above named product features and inspect dev console or network tab.

**Comment by chriskacerguis** [comment]
Moved here: https://www.pivotaltracker.com/story/show/134431553
