### ISSUE TITLE
Switch to use angular-patternfly-sass so patternfly variables are available

### ISSUE THREAD

**Issue by jeff-phillips-18** [ManageIQ/manageiq-ui-service#384]
Currently lots of colors are defined that do not follow the patternfly color palette. Mixing patternfly components and custom components gives varying shades of colors. It would be better to use the color variables from patternfly to keep consistency between components.

**Comment by chriskacerguis** [comment]
Closing.  Tracking here - https://www.pivotaltracker.com/story/show/136027823
