### ISSUE TITLE
Dialog field visibility is not honored on dynamic fields in Service UI

### ISSUE THREAD

**Issue by evenit** [ManageIQ/manageiq-ui-service#497]
When creating dialogs with dynamic fields, programmatic visibility works as expected in the Classic UI, but not in the Service UI. For example, I create a dialog with two fields: one drop down with 'Yes' and 'No' as values and one dynamic text box. The drop down is configured to refresh other fields and the text box is auto refreshed. The code for the dynamic text box is a one liner:

```ruby
$evm.object['visible'] = $evm.root['dialog_element1'] == 'Yes'
```

I then create a generic service catalog item using this dialog. When ordering this item in the Classic UI, the dynamic text box visibility is honored based on the drop down value. When ordering this item in the Service UI, the text box stays visible whatever the value of the drop down.

I added a third field in the dialog, statically invisible. It stays invisible in both UI, so the bug seems only related to dynamic fields in the Service UI.

**Comment by chriskacerguis** [comment]
Tracking here: https://www.pivotaltracker.com/story/show/139238997

**Comment by chriskacerguis** [comment]
This was addressed with https://github.com/ManageIQ/manageiq-ui-service/pull/587
