### ISSUE TITLE
Service UI (SUI) Kerberos SSO

### ISSUE THREAD

**Issue by ITD27M01** [ManageIQ/manageiq-ui-service#640]
Hi guys. I have configured ManageIQ appliance for external httpd auth from this guide: http://manageiq.org/docs/reference/latest/auth/active_directory
I turned on "Enable Single Signon" checkbox and have simple access to Classic UI. Is there any way to enable it for the Service UI? I think it will be a killer feature for the end users.

**Comment by chriskacerguis** [comment]
So, the SUI is just a consumer of the MIQ API, so all we do is pass the credentials to the API.  So by enabling it there, whatever it supports we support.

**Comment by ITD27M01** [comment]
@chriskacerguis  I have access to Classic UI trough SSO - just enter link to browser and auto login. But if I access /self_service URL there is login/password prompt and no auto login to interface.

**Comment by chriskacerguis** [comment]
Hmmm...not sure where the issue could be (API vs. SUI).  

@jjlangholtz any thoughts here?

**Comment by jjlangholtz** [comment]
I know prior to https://github.com/ManageIQ/manageiq-ui-service/pull/528 this just did not work at all. Are you using the latest errata release?

Other than that I'm not sure. I know there were some recent discussions around groups and permissions but I'm not sure whether that applies here either.

**Comment by ITD27M01** [comment]
@jjlangholtz 
I use euwe-2 and tried to pull to latest commit (#642) but no effect. But it seems that this commit has solved my issue with pop-up tooltip :)

**Comment by chriskacerguis** [comment]
@gtanzillo Any thoughts on this?  We are using the token auth, so not sure why this isn't working.

**Comment by gtanzillo** [comment]
@chriskacerguis I'd also expect this to work. Both the classic UI and SUI use the API for logon. If SSO is working properly with the classic UI, I'd expect it to work with the SUI. @abellotti, any ideas?

**Comment by chriskacerguis** [comment]
@martinpovolny or @himdel for login to the Classic UI, do you all use the token method?  I know there are 2 login methods (token, and the more "classic" way).

**Comment by abellotti** [comment]
Not necessarily, API entrypoint in Apache supports logging in with external auth credentials, (ldap/ipa/ad), but not SSO.  Kerberos SSO was never implemented for self-service, it is handled via browser SPNEGO protocol and dealt with via the /dashboard/kerberos_authenticate directive in the Apache config, so right now only for classic UI.  Kerberos and SAML logic in the classic UI controller have special handling for generating the API tokens needed.

**Comment by chriskacerguis** [comment]
Thanks @abellotti

**Comment by chriskacerguis** [comment]
Tracking this here: https://www.pivotaltracker.com/story/show/143796185

**Comment by chriskacerguis** [comment]
Waiting for: https://www.pivotaltracker.com/n/projects/1610125/stories/144136505

**Comment by chriskacerguis** [comment]
BZ RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1451012

**Comment by chriskacerguis** [comment]
Closing this, work should be done from BZ.
