### ISSUE TITLE
Service UI cockpit button redirects to IP instead of hostname or fqdn.

### ISSUE THREAD

**Issue by ITD27M01** [ManageIQ/manageiq-ui-service#641]
The cockpit button for the instance of the deployed service redirects to the ip address of the instance. This redirection causes certificate warning and does not allow SSO authentication in a domain environment. I understand that in order to guarantee the connection you want to exclude third-party technologies such as DNS. But maybe I can do something to change this behavior for my environment ?

**Comment by chriskacerguis** [comment]
If you would like to change it in your environment, you can change this line of code:

https://github.com/ManageIQ/manageiq-ui-service/blob/90081938e2e02a4b781b52e1f92933726e4e7441/client/app/services/service-details/service-details.component.js#L332

to reference the hostname and not the IP address.  That said, I don't know if MIQ will necessarily know the hostname in all scenarios.

**Comment by ITD27M01** [comment]
@chriskacerguis I have not found the path specified in euwe-2, as I understand it, the path is for darga.
https://github.com/ManageIQ/manageiq-ui-service/tree/euwe/client/app/services

**Comment by ITD27M01** [comment]
@chriskacerguis Found it in client/app/services/consoles.service.js
