### ISSUE TITLE
Dynamic dropdown list does not show data at startup

### ISSUE THREAD

**Issue by ITD27M01** [ManageIQ/manageiq-ui-service#655]
Hi Guys.
Two more cents from me.

In SUI when ordering the service, dynamic drop-down list does not want to show the values at startup. The value is loaded but the first line is blank until I click on the drop-down list.

![image](https://cloud.githubusercontent.com/assets/3703483/24819378/0832709a-1bed-11e7-9799-7bd57b8c280b.png)

![image](https://cloud.githubusercontent.com/assets/3703483/24819653/2f20ebcc-1bee-11e7-82a7-37f721e1cb12.png)

Classic UI have expected behavior:

![image](https://cloud.githubusercontent.com/assets/3703483/24819440/4c5c3c38-1bed-11e7-9fd8-30fcef98b448.png)

There is my configuration for dropdowns:

![image](https://cloud.githubusercontent.com/assets/3703483/24819696/5ae97bfc-1bee-11e7-8b1d-be66db361e38.png)

![image](https://cloud.githubusercontent.com/assets/3703483/24819491/784956dc-1bed-11e7-9e79-68c903469feb.png)

And my code for flavors:

```
  ems = $evm.vmdb('ext_management_system').where(:id => $evm.root['dialog_cloud'])[0]

  filter = Regexp.new($evm.object['flavor'].to_s)

  flavors_for_users = ems.flavors.select { |flavor| flavor.name =~ filter }
  $evm.log("info", "flavors_for_users - #{flavors_for_users}")

  flavors = flavors_for_users.sort_by {|flavor| flavor.memory}
  $evm.log("info", "Sorted flavors_for_users - #{flavors}")
  
  values_hash = {}

  flavors.each do |flavor|
    flavor_id = flavor['id'].to_i
    flavor_name = flavor['name'].to_s
    values_hash[flavor_id] = flavor_name
  end

  list_values = {
     'auto_select_single' => true,
     'sort_by'            => :none,
     'data_type'          => :string,
     'required'           => true,
     'values'             => values_hash
  }

  list_values.each do |key, value| 
    $evm.object[key] = value
  end
``````

**Comment by chriskacerguis** [comment]
The blank is there by design, so dynamic dropdown work correctly.

**Comment by ITD27M01** [comment]
@chriskacerguis  Hello, Thank You for reply.
It's a bit confusing for me and my users. In a yaml configuration of dialogs there is a setting "default_value" and apparently SUI do not use it. By design could be an empty string in the dropdown list without a default value, but when you want to use the default values, drop down list should show this default value and not a null value.
You need to take into consideration that if you click the order button, the default values specified in the dialog are used to deploy virtual machines, even though they are not shown in drop-down list.
