### ISSUE TITLE
"Multiselect" DropDown does not work in SUI

### ISSUE THREAD

**Issue by ITD27M01** [ManageIQ/manageiq-ui-service#686]
Hi guys.
The "multiselect" options for DropDown list does not work in SUI. I cannot select multiple values for this type of element form SUI but can do it from classic ui:
Screen frim Classic UI:
![image](https://cloud.githubusercontent.com/assets/3703483/25178505/b195b2d0-250e-11e7-82ab-e86c145f4dc3.png)
Screen from SUI:
![image](https://cloud.githubusercontent.com/assets/3703483/25178657/74f1b4f4-250f-11e7-8b64-9ff36d52b6f7.png)

**Comment by AllenBW** [comment]
Whattup @ITD27M01 !  ok so off the bat, from where are you accessing the multiselect dropdown?  

this matters because it might be an issue better suited for https://github.com/ManageIQ/ui-components

**Comment by ITD27M01** [comment]
Hi @AllenBW I'm trying to set up a dynamic dialog for the service. One of the elements of such a dialog is a drop-down list with multiselect parameter.

**Comment by chriskacerguis** [comment]
Hello @ITD27M01,

Where are you accessing the multiselect dropdown?

**Comment by ITD27M01** [comment]
@chriskacerguis 
From SUI during Service Request. Service have dynamic dialog with dropdown element with "multiselect" option:
![image](https://cloud.githubusercontent.com/assets/3703483/25225309/a7819a46-25c9-11e7-912c-85c525ea12c5.png)

**Comment by chriskacerguis** [comment]
Yeah, I think this needs to go to https://github.com/ManageIQ/ui-components
