### ISSUE TITLE
Orders should be "My Orders" 

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#734]
<img width="257" alt="screen shot 2017-05-02 at 11 05 05 pm" src="https://cloud.githubusercontent.com/assets/12504403/25646969/e034afec-2f8b-11e7-9472-2815b61a9e22.png">

**Comment by chriskacerguis** [comment]
Tracking here: https://www.pivotaltracker.com/story/show/144790949

**Comment by chriskacerguis** [comment]
Resolved by PR #736
