### ISSUE TITLE
Users should be able to click anywhere on the row to drill down on a service

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-ui-service#735]
Users should be able to click anywhere on the row to drill down on a service.  This behavior has been changed from the previous release.  Now you can only drill down by clicking on the service name, this decreases usability.

**Comment by chriskacerguis** [comment]
Tracking here: https://www.pivotaltracker.com/story/show/144791027

**Comment by chriskacerguis** [comment]
Resolved with PR: https://github.com/ManageIQ/manageiq-ui-service/pull/737
