### ISSUE TITLE
Include icons provided by font-fabulous

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-ui-service#850]
@epwinchell created a custom fonticon set for our needs. As we want to support [fonticons on custom buttons](https://github.com/ManageIQ/manageiq-ui-service/pull/851), we need this iconset to be included in the SUI.

You can find the repo here: https://github.com/ManageIQ/font-fabulous
There is (untested) support for npm/yarn, but we haven't pushed any versions yet.
If you need a version or some extra modifications in the `package.json`, let me know.

Thanks

**Comment by AllenBW** [comment]
Closed by#851 and #854
