### ISSUE TITLE
how to change custom brand programmatically?

### ISSUE THREAD

**Issue by meng-tian** [ManageIQ/manageiq-ui-service#853]
Description of problem:

I know we can change the custom logo through web UI. But can we change the custom logo programmatically? i.e., save a image while deploying the instance without manually upload through the web UI.

**Comment by chriskacerguis** [comment]
You could just change the appropriate image in: client/assets/images

The README here has more in depth info: https://github.com/ManageIQ/manageiq-ui-service/tree/master/skin-sample

**Comment by meng-tian** [comment]
I tried but it does not have any effect. Do I need to recompile or clear cache?

**Comment by chriskacerguis** [comment]
What version are you running?

**Comment by meng-tian** [comment]
fine-2

**Comment by chriskacerguis** [comment]
sounds like it is hitting the webpack cache, so you would need to rebuild.

**Comment by meng-tian** [comment]
I tried to use the `yarn build` (I followed the README page you provided), still no effect.

**Comment by meng-tian** [comment]
Anyone help?

**Comment by AllenBW** [comment]
Hi @meng-tian !  If you want to add you own custom login logo and custom logo try dropping the file s in the highlighted folder.  Be mindful of the filenames 🌮 🌞 🎵 
<img width="328" alt="screen shot 2017-07-28 at 7 32 42 am" src="https://user-images.githubusercontent.com/6640236/28715640-f8fde484-7366-11e7-9800-58632e316719.png">

**Comment by meng-tian** [comment]
Thanks for you reply @AllenBW . I tried your method and I can see the custom logo in `Configuration -> Server -> Custom Logos` has changed. However, the upright corner logo and login page logo is still using the old logo. Restarted the httpd but does not help.

Do I need to clear the cache or recompile?

**Comment by AllenBW** [comment]
@meng-tian ahh looks like the work to get custom_logo/brand into the sui didn't make it in to fine-2, https://github.com/ManageIQ/manageiq-ui-service/pull/769.  Apologies, shoulda checked that to boot, explains why you see nothing :-/
