### ISSUE TITLE
Show details of Generic Objects at the Service Level

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#934]
As a user, I should be able to see details of a Generic Object at the Resource Level

<img width="634" alt="screen shot 2017-09-11 at 11 58 02 am" src="https://user-images.githubusercontent.com/2414647/30284298-828c2586-96e8-11e7-8f99-57fe6288dcb2.png">

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497705

**Comment by chriskacerguis** [comment]
Awaiting backend from @ManageIQ/core-api

**Comment by chriskacerguis** [comment]
@serenamarie125  Something that came up is that there is no way to see tags associated with the generic objects via the Service UI.

@bascar is that something we should add?

/cc @Loicavenel

**Comment by bascar** [comment]
@chriskacerguis agreed, should be like vm detailed view tag control. @serenamarie125 can you please add this.

**Comment by chalettu** [comment]
@serenamarie125 I had a few questions about the mockup for this request.  In the picture above we see a "g" icon used for each generic object.  Is this an icon we have available that we are wanting to use to represent generic objects?  I looked in patternfly and couldn't find it.  I also wanted to see if you could help elaborate on what menu actions are expected to exist for that Kebab menu that is part of the UI mock.

**Comment by Loicavenel** [comment]
@chalettu Menu Actions are completely dynamic and will come from the API

**Comment by bascar** [comment]
@chalettu see ManageIQ/manageiq#16006 as relates to the picture question above. Sorry posted this on the wrong issue earlier

**Comment by chriskacerguis** [comment]
Here's the design doc

https://docs.google.com/a/redhat.com/document/d/1oBVIJNk-X_XoUDun2RHpg2Hp0Sp6ljwPrGxGlV0UyfE
