### ISSUE TITLE
For every element add a help button with a description

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#935]
I want to see an help button for every element with a description, then I can use with my mouse over to get information

**Comment by chriskacerguis** [comment]
Awaiting backend from @ManageIQ/core-api

**Comment by Loicavenel** [comment]
@chriskacerguis does it really requires a new API? It is going to be part of Dialogs, do we not get all Dialogs parameters already?

**Comment by chriskacerguis** [comment]
We need an addition to the existing api that has the new help data

**Comment by chriskacerguis** [comment]
Spoke to @Loicavenel (via email) per his email:

>  I will reply to the PR. All customer are using Description already today for this exact reason (when you put your mouse over the name of the field, we show the description). If we had another field, all Dialogs will not show the message anymore. SO, smart and faster way, just use existing Description… on the editor part we will rename it “Help Text” and we are good :)


Checked the code, and this is there: https://github.com/ManageIQ/ui-components/blob/master/src/dialog-user/components/dialog-user/dialogField.html#L9
