### ISSUE TITLE
When I duplicate an existing order I want to be able to modify dialog inputs

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#937]
As a user, when I duplicate an existing order I want to be able to modify dialog inputs

**Comment by chriskacerguis** [comment]
@serenamarie125 I found a Google Doc that was not complete regarding this.  Do we need a wireframe, or should we just re-prompt with the current dialog system and the fields filled in?

/cc @Loicavenel

**Comment by serenamarie125** [comment]
@chriskacerguis doc has been updated and approved by @Loicavenel ... let me know if you have any questions
https://docs.google.com/document/d/16A3j1FYwnCIDppLDB3-lB7cfzcDWOfFlCRy5_b47clg/
