### ISSUE TITLE
Events at the Resource Details Level and drill down to more details information

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#939]
As a user, I want to see Events at the Resource Details Level and drill down to more details information by changing time, history etc.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497721

**Comment by serenamarie125** [comment]
@chriskacerguis Take a look at this doc: https://docs.google.com/document/d/1kvWtq4xFX4Upqm5dfws8g6Z4OxBOzwjBH3hmIv608cc/

You should be able to click on the View All link in the Timeline card, and go to a full blown timeline view for the VM

**Comment by chriskacerguis** [comment]
@serenamarie125 is the "full blown timeline view" a new page?  If so, do we have a wireframe of what that page will look like?

**Comment by chriskacerguis** [comment]
Per lined add by @serenamarie125 to the above Google doc:

> The Full View of a timeline view should match the Ops UI Implementation

Screenshots from Ops UI:

<img width="1059" alt="screen shot 2017-09-13 at 9 30 40 am" src="https://user-images.githubusercontent.com/2414647/30380033-6c9278f0-9866-11e7-8b74-abcb6510b65c.png">

<img width="1048" alt="screen shot 2017-09-13 at 9 31 10 am" src="https://user-images.githubusercontent.com/2414647/30380046-72b1139a-9866-11e7-9a15-d95c3227363a.png">

<img width="1044" alt="screen shot 2017-09-13 at 9 32 42 am" src="https://user-images.githubusercontent.com/2414647/30380064-86239984-9866-11e7-9de9-93717a62f08a.png">

@serenamarie125 could you please confirm that this is what we should build?

**Comment by serenamarie125** [comment]
@chriskacerguis yes

**Comment by chriskacerguis** [comment]
working off of BZ
