### ISSUE TITLE
Add popup utilization graph at the Resource Details Level

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#940]
As a user, I want to see utilisation graph at the Resource Details Level and I can drill down to more details information by changing time, duration, etc

<img width="628" alt="30284330-9ef8afa0-96e8-11e7-9def-15d8b97237bd" src="https://user-images.githubusercontent.com/2414647/30289240-82ac8392-96f9-11e7-8724-46f6bb1bbecd.png">

**Comment by chriskacerguis** [comment]
@serenamarie125 and @Loicavenel how does a user change the date / time range for this?

**Comment by serenamarie125** [comment]
@Loicavenel given that trends have been removed, and we are showing utilization at a point in time, I'm not sure that is possible.

When looking at the dashboard, you are seeing an aggregation of utilization in the donut chart.  When you click on the donut, you are able to see the contributing resources. 

Are we missing anything here @Loicavenel ?  I'm assuming the wording is based on when we thought we had the ability to see trends and change the time period.

**Comment by Loicavenel** [comment]
@serenamarie125 Trends should be available when we have the appropriate APIs. We need to sit down and review the Service Dashboard and the flow.

**Comment by chriskacerguis** [comment]
Closing, moving to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1514073
