### ISSUE TITLE
Events at the Resource Details Level and drill down to more details

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#941]
As a user, I want to see Events at the Resource Details Level and drill down to more details information by changing time, history etc.

**Comment by chriskacerguis** [comment]
@AllenBW do we have a wireframe for this?

**Comment by AllenBW** [comment]
[from here we have this: ](https://docs.google.com/document/d/1kvWtq4xFX4Upqm5dfws8g6Z4OxBOzwjBH3hmIv608cc/edit#heading=h.kcee6dc8myrz)
<img width="643" alt="screen shot 2017-09-12 at 8 55 55 am" src="https://user-images.githubusercontent.com/6640236/30326945-475d9886-9798-11e7-920f-f4d81afd8b90.png">

**Comment by chriskacerguis** [comment]
Dup of https://github.com/ManageIQ/manageiq-ui-service/issues/939
