### ISSUE TITLE
Ability to open events UI of a resource at Service Level

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#942]
As a user, I want to be able to open events UI of a resource at Service Level

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497721

**Comment by chriskacerguis** [comment]
@serenamarie125 I know we talked about this, and I know there **is** a screen for this, but I couldn't find it.  Could you please re-send it to me?

**Comment by serenamarie125** [comment]
@chriskacerguis when going to a service, and selecting a VM, you are able to see the timeline view. This should be sufficient as far as I am aware.
Documentation for the VM Detail view can be found here: https://docs.google.com/document/d/1kvWtq4xFX4Upqm5dfws8g6Z4OxBOzwjBH3hmIv608cc/

**Comment by chriskacerguis** [comment]
Hi @serenamarie125 apologies, I'm confused.  Loic's requirement is asking for the Service Level, whereas what you said appears to be the resource level (but, maybe I'm having a bad case of the dumb today).

@Loicavenel could you please clarify if which direction you want to go?  Is the Resource level sufficient or do we need to have this at the Service Level (we scoped this requirement with the API team, so they are expecting to build a rollup)

**Comment by Loicavenel** [comment]
@serenamarie125 and @chriskacerguis Ok, I think I remember it and I understand the confusion here. What is confusing is "resource" in the title. 
If you go to a resource, you have a timeline here with a limited item power... you should be able to for to the classic timeline with full option. 
I think the discussion we have was to see a Timeline at Service Level for all resources like an aggregation of all events.. I am not sure we have an API for it.

**Comment by chriskacerguis** [comment]
@Loicavenel there is no API, it will need to get built, but it is "on the schedule".  So, if we don't want to go in that direction, I'll let the API team know.

**Comment by Loicavenel** [comment]
@chriskacerguis I think we need this API, I want to make sure we are talking about the same thing, this API will provide all Events for a Service?

**Comment by chriskacerguis** [comment]
@serenamarie125 should we just use the same screen from here (just will all the Service Level data)

**Comment by chriskacerguis** [comment]
@Loicavenel Yes, this API will provide a roll up of all events for resources in the service.

**Comment by serenamarie125** [comment]
@Loicavenel i was under the impression that we dropped this requirement.  If not, we need to think this through ... from a requirements perspective.

**Comment by Loicavenel** [comment]
@serenamarie125 We need Events Timeline at the resource (VM here) level and I think we are on an agreement here, user will go to VM detail where he will see a timeline for Power Event, he will be able to click on "View All" that will open the "full" time line view for this VM.

The other requirement here is to have a Timeline view for all VMs in the Service... We don't want to have an option for user to open Timeline for a VM from the Service View but I think we want to have a Timeline view of the service itself... Does it make sense? I am sorry if I was not clear.

**Comment by Loicavenel** [comment]
It is not mandatory for 4.6

**Comment by chriskacerguis** [comment]
working of BZ for this moving forward.
