### ISSUE TITLE
Ability to see last event at Service Level for all resource by expanding resource line

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#943]
Ability to see last event at Service Level for all resource by simply expanding the resource line

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497719

**Comment by chriskacerguis** [comment]
@serenamarie125 I couldn't find a wireframe that had this on it.  Could you give me a hint as to where to find it?

/cc @Loicavenel

**Comment by serenamarie125** [comment]
@Loicavenel 2 questions
1 - would this just be for VMs or Generic Objects too?  To date we have only designed expandable list views for these 2 resource types.  
2 - what's necessary to display, timestamp & message?

**Comment by chriskacerguis** [comment]
@Loicavenel ping :)

**Comment by Loicavenel** [comment]
@serenamarie125

1 -  We are not getting any event for Generic Object then it is not needed.
2 - Message and Time stamp will be enough

**Comment by chriskacerguis** [comment]
Closing this, work should be done from BZ.
