### ISSUE TITLE
Investigate moving to TypeScript

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#985]
Keeping with the UI-Components repo, wondering if we should moving the SUI to use TypeScript?

Thoughts @ohadlevy @martinpovolny @AllenBW @himdel @ManageIQ/core-ui-classic

**Comment by AllenBW** [comment]
So you thinking a side by side thing? JS and TS?  Imma kinda against it either way, love staying pure to JS, who remembers coffeescript (don't answer that, and yes I know 2.x came out recently)? Not saying TS is bad, it has many uses, but the only reason I see for moving the SUI over to TS is for unity of UIs, but lets face it, thats kinda impossible without a full rewrite of both (though I would **LOVE** incorporating some `hamlit` html is a messssssss)

**Comment by martinpovolny** [comment]
The OPS UI is just enabling TypeScript, not enforcing it.

The SUI contributors are a small group of experienced developers and there already is a code structure, culture and standards that are sort of enforced.

I'd say that there's probably no immediate benefit from moving SUI to TypeScript.

Especially if all the developers are happy with javascript I see no reason to enforce TypeScript ;-)

**Comment by chalettu** [comment]
I agree with @martinpovolny on no immediate benefit.  Just so it's on record, it has been enabled in SUI and we could be writing in Typescript.  We haven't tested it in the SUI lately but it should be working.  I don't see a benefit to moving currently.  If we migrate to a newer framework we should most definitely revisit this discussion though as it impacts coding style.

**Comment by chriskacerguis** [comment]
@martinpovolny sure, I guess I was just wondering if (thinking way down the road) moving to TypeScript is something that would help us merge the UIs.  What do you think?

**Comment by martinpovolny** [comment]
@chriskacerguis : I am not presently contributing to that code so I don't have any strong opinion. I'd leave this to @chalettu and @AllenBW. From my perspective it is not needed. Especially if it is actually possible to write in Typescript as @chalettu wrote above, I don't see a reason to change anything at this point.

**Comment by chriskacerguis** [comment]
@ohadlevy any thoughts?

**Comment by chriskacerguis** [comment]
Doesn't seem like we have consensus.  Closing, we can revisit later if wanted.
