### ISSUE TITLE
Create and display a git SHA for the current SUI Build

### ISSUE THREAD

**Issue by chalettu** [ManageIQ/manageiq-ui-service#999]
Description of problem:  Currently the SUI does not package and display a GIT SHA that is indicative of current version of code that is part of a build. 

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:  I think this should be added into our webpack build steps.  We should run something that generates that GIT SHA and saves it to a JSON file.  The SUI about modal should consume that modal.

**Comment by chriskacerguis** [comment]
@chalettu please remember to close out your issues when done :)
